### ISSUE TITLE
+war profile seems broken by default

### ISSUE THREAD

**Issue by martinbalfanz** [luminus-framework/luminus#128]
I'm trying to use luminus with the `+war` profile (and also `+swagger +h2` in case it matters) and I run into the following on `lein run` without any modifications to the generated project:

```
[2016-04-30 22:21:21,622][DEBUG][org.jboss.logging] Logging Provider: org.jboss.logging.Log4jLoggerProvider
[2016-04-30 22:21:22,828][INFO][lumi-test.env]
-=[lumi-test started successfully using the development profile]=-
Exception in thread "main" java.lang.RuntimeException: could not start [#'lumi-test.core/http-server] due to, compiling:(/private/var/folders/c6/npth4rmj4wbddccbfx46xtg00000gn/T/form-init3841533603883677885.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: could not start [#'lumi-test.core/http-server] due to
	at mount.core$up$fn__100.invoke(core.cljc:92)
	at mount.core$up.invokeStatic(core.cljc:92)
	at mount.core$up.invoke(core.cljc:90)
	at mount.core$bring.invokeStatic(core.cljc:206)
	at mount.core$bring.invoke(core.cljc:198)
	at mount.core$start.invokeStatic(core.cljc:246)
	at mount.core$start.doInvoke(core.cljc:242)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at mount.core$start_with_args.invokeStatic(core.cljc:312)
	at mount.core$start_with_args.doInvoke(core.cljc:308)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at lumi_test.core$start_app.invokeStatic(core.clj:44)
	at lumi_test.core$start_app.invoke(core.clj:42)
	at lumi_test.core$_main.invokeStatic(core.clj:59)
	at lumi_test.core$_main.doInvoke(core.clj:51)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval20540.invokeStatic(form-init3841533603883677885.clj:1)
	at user$eval20540.invoke(form-init3841533603883677885.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more
Caused by: clojure.lang.ArityException: Wrong number of args (0) passed to: middleware/wrap-internal-error/fn--16378
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:28)
	at lumi_test.core$eval20421$fn__20422.invoke(core.clj:21)
	at mount.core$record_BANG_.invokeStatic(core.cljc:86)
	at mount.core$record_BANG_.invoke(core.cljc:85)
	at mount.core$up$fn__100.invoke(core.cljc:93)
	... 35 more
```

**Comment by yogthos** [comment]
Ah ok, that was a regression introduced by this fix https://github.com/luminus-framework/luminus-template/issues/220 the `app` is now a function, but this doesn't work when using an uberwar. I just pushed out a fix, so making a new project should work correctly now.

**Comment by martinbalfanz** [comment]
Great, thanks! Sorry for posting the issue on the wrong repository, I just noticed that this belongs to luminus-template.

**Comment by yogthos** [comment]
no worries, and thanks for opening the issue for this
