### ISSUE TITLE
New project with +service profile does not build

### ISSUE THREAD

**Issue by dgoeke** [luminus-framework/luminus#136]
To reproduce:

```
~/repos $ lein new luminus test-app +service
Generating a Luminus project.
~/repos $ cd test-app
~/r/test-app $ lein repl
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.RuntimeException: Unable to resolve symbol: wrap-webjars in this context, compiling:(test_app/middleware.clj:12:7)
        at clojure.lang.Compiler.analyze(Compiler.java:6688)
        at clojure.lang.Compiler.analyze(Compiler.java:6625)
```

Other lein tasks like uberjar fail with the same error.  The problem is solved by removing the line "webjars" from `test-app.middleware/wrap-base`.

**Comment by yogthos** [comment]
ah sorry about that, introduced a regression fixing this issue https://github.com/luminus-framework/luminus-template/issues/234 I'll push a new version out shortly

**Comment by yogthos** [comment]
ok pushed out the fix for this
