### ISSUE TITLE
Trouble with cider and figwheel using luminus template

### ISSUE THREAD

**Issue by Engelberg** [luminus-framework/luminus#193]
I started a fresh template using +cljs and +hoplon.

I updated Clojure to 1.9.0-alpha16.

Using cider-jack-in-clojurescript, I get the following error after figwheel repl connects to the browser:

```
1. Unhandled java.lang.Exception
   Failed to launch Figwheel CLJS REPL: nREPL connection found but
   unable to load piggieback.  This is commonly caused by A) not
   providing piggieback as a dependency and/or B) not adding
   piggieback middleware into your nrepl middleware chain.
   
   example profile.clj code: ----- :profiles {:dev {:dependencies
   [[com.cemerick/piggieback <current-version>]
   [org.clojure/tools.nrepl <current-version>]] :repl-options
   {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}}} -----
   Please see the documentation for piggieback here
   https://github.com/cemerick/piggieback#installation
   
   Note: Cider will inject this config into your project.clj.  This
   can cause confusion when your are not using Cider.

                  repl.clj:  166  figwheel-sidecar.repl/eval28850/fn
              MultiFn.java:  233  clojure.lang.MultiFn/invoke
                  repl.clj:  305  figwheel-sidecar.repl/repl
                  repl.clj:  303  figwheel-sidecar.repl/repl
               RestFn.java:  436  clojure.lang.RestFn/invoke
                system.clj:  510  figwheel-sidecar.system/start-figwheel-repl
                system.clj:  501  figwheel-sidecar.system/start-figwheel-repl
                system.clj:  574  figwheel-sidecar.system/figwheel-cljs-repl*
                system.clj:  572  figwheel-sidecar.system/figwheel-cljs-repl*
                system.clj:  595  figwheel-sidecar.system/cljs-repl*
                system.clj:  587  figwheel-sidecar.system/cljs-repl*
                system.clj:  621  figwheel-sidecar.system/start-repl
                system.clj:  615  figwheel-sidecar.system/start-repl
                system.clj:  619  figwheel-sidecar.system/start-repl
                system.clj:  615  figwheel-sidecar.system/start-repl
                  AFn.java:  160  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  659  clojure.core/apply
                  core.clj:  652  clojure.core/apply
                system.clj:  629  figwheel-sidecar.system/cljs-repl
                system.clj:  627  figwheel-sidecar.system/cljs-repl
               RestFn.java:  421  clojure.lang.RestFn/invoke
              repl_api.clj:  114  figwheel-sidecar.repl-api/cljs-repl
              repl_api.clj:  107  figwheel-sidecar.repl-api/cljs-repl
              repl_api.clj:  111  figwheel-sidecar.repl-api/cljs-repl
              repl_api.clj:  107  figwheel-sidecar.repl-api/cljs-repl
                      REPL:    1  user/eval78096
                      REPL:    1  user/eval78096
             Compiler.java: 6977  clojure.lang.Compiler/eval
             Compiler.java: 6967  clojure.lang.Compiler/eval
             Compiler.java: 6940  clojure.lang.Compiler/eval
                  core.clj: 3187  clojure.core/eval
                  core.clj: 3183  clojure.core/eval
                  main.clj:  242  clojure.main/repl/read-eval-print/fn
                  main.clj:  242  clojure.main/repl/read-eval-print
                  main.clj:  260  clojure.main/repl/fn
                  main.clj:  260  clojure.main/repl
                  main.clj:  176  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  657  clojure.core/apply
                  core.clj:  652  clojure.core/apply
                regrow.clj:   18  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  657  clojure.core/apply
                  core.clj: 1963  clojure.core/with-bindings*
                  core.clj: 1963  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   85  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   55  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  222  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
    interruptible_eval.clj:  190  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                  AFn.java:   22  clojure.lang.AFn/run
   ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
   ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
               Thread.java:  745  java.lang.Thread/run
```

To try to solve the problem, I tried adding ` [org.clojure/tools.nrepl "0.2.10"]` to the dev dependencies, and I also tried moving off the piggieback SNAPSHOT to version 0.2.1.  Neither helped.

I believe it worked for me at some point in the past, but something recent has changed (that's why I initially suspected the SNAPSHOT of piggieback).  It appears to me that the profile has all the elements which the error message says to check for, so I'm a bit stumped.

Any ideas what could be going wrong?

**Comment by yogthos** [comment]
Unfortunately, not quite sure what's causing that. It does look like the right dependencies are being loaded, since I don't use cider myself I'm not familiar with the details of how it injects itself.

**Comment by Engelberg** [comment]
Are you aware of any issues with the new changes to spec in 1.9.0-alpha16?

**Comment by Engelberg** [comment]
In an effort to simplify, I've found that I'm getting a seemingly-related error message with the basic luminus +cljs template with no modifications, run from the command line and not from cider.  So maybe it's a luminus issue after all?  Here are my steps to reproduce.  Can you try this out?  Thanks:

1. `lein new luminus luminuscljs +cljs`
2. Open command prompt, navigate to luminuscljs directory.
3. `lein run`
4. Open another command prompt, navigate to luminuscljs directory.
5. `lein figwheel`
6. After the figwheel repl starts up, wait a few moments.
7. In your browser (I used Chrome), open localhost:3000.
8. Wait a few more minutes, and you should see the error appear in the figwheel command prompt window.

I think it was working for me last week, so I'm really baffled.

**Comment by Engelberg** [comment]
The error message I'm seeing in the terminal looks like this:

```
Prompt will show when Figwheel connects to your application
clojure.lang.ExceptionInfo: Eval timed out! {:type :js-eval-exception, :error {:status :exception, :value "Eval timed out!", :stacktrace "No stacktrace available."}, :repl-env #figwheel_sidecar.repl.FigwheelEnv{:figwheel-server #figwheel_sidecar.components.figwheel_server.FigwheelServer{:connection-count #object[clojure.lang.Atom 0x4249543f {:status :ready, :val {"app" 1}}], :browser-callbacks #object[clojure.lang.Atom 0x3d91b738 {:status :ready, :val {"figwheel-repl-print" #object[figwheel_sidecar.repl$add_repl_print_callback_BANG_$fn__25330 0x3f4d16be "figwheel_sidecar.repl$add_repl_print_callback_BANG_$fn__25330@3f4d16be"], "figwheel_callback_50094" #object[figwheel_sidecar.components.figwheel_server$setup_callback$fn__25197 0x4b30cf9a "figwheel_sidecar.components.figwheel_server$setup_callback$fn__25197@4b30cf9a"]}}], :output-dir "target/cljsbuild/public/js/out", :ring-handler nil, :file-change-atom #object[clojure.lang.Atom 0x22b148d5 {:status :ready, :val ({:msg-name :repl-eval, :code "cljs.core._STAR_print_namespace_maps_STAR_ = true", :figwheel-version "0.5.10", :build-id "app", :callback-name "figwheel_callback_50094"})}], :compile-wait-time 10, :builds {"app" {:source-paths ["src/cljs" "src/cljc" "env/dev/cljs"], :figwheel {:on-jsload "luminuscljs.core/mount-components", :build-id "app"}, :id "app", :watch-paths ["src/cljs" "src/cljc" "env/dev/cljs"], :compile-paths ["src/cljs" "src/cljc" "env/dev/cljs"], :build-options {:main "luminuscljs.app", :asset-path "/js/out", :output-to "target/cljsbuild/public/js/app.js", :output-dir "target/cljsbuild/public/js/out", :source-map true, :optimizations :none, :pretty-print true, :source-map-timestamp true}, :compiler-env #object[clojure.lang.Atom 0x23ad20c0 {:status :ready, :val #CompilerEnv{}}]}}, :repl-print-chan #object[clojure.core.async.impl.channels.ManyToManyChannel 0x2bcd7026 "clojure.core.async.impl.channels.ManyToManyChannel@2bcd7026"], :nrepl-port 7002, :server-port 3449, :output-to "target/cljsbuild/public/js/app.js", :ansi-color-output true, :resolved-ring-handler nil, :build-id "app", :server-ip "0.0.0.0", :cljs-build-fn #object[figwheel_sidecar.components.cljs_autobuild$color_output$fn__26657 0x1b552a10 "figwheel_sidecar.components.cljs_autobuild$color_output$fn__26657@1b552a10"], :http-server #object[clojure.lang.AFunction$1 0x338a2e4f "clojure.lang.AFunction$1@338a2e4f"], :open-file-command nil, :unique-id "C:\\Temp\\luminuscljs", :nrepl-middleware [cemerick.piggieback/wrap-cljs-repl], :log-writer #object[java.io.BufferedWriter 0x79ebb3de "java.io.BufferedWriter@79ebb3de"], :file-md5-atom #object[clojure.lang.Atom 0x39e7b085 {:status :ready, :val {}}], :css-dirs ["resources/public/css"], :http-server-root "public", :figwheel-sidecar.repl/repl-writers #object[clojure.lang.Atom 0xbd01803 {:status :ready, :val {#'clojure.core/*math-context* nil, #'cljs.repl/*cljs-verbose* nil, #<Var: --unnamed--> nil, #'clojure.core/*print-level* nil, #<Var: --unnamed--> 1, #'cljs.analyzer/*unchecked-if* false, #'clojure.core/*command-line-args* nil, #<Var: --unnamed--> 1, #'cljs.env/*compiler* #object[clojure.lang.Atom 0x23ad20c0 {:status :ready, :val #CompilerEnv{}}], #'clojure.core/*err* #object[java.io.PrintWriter 0x210e358 "java.io.PrintWriter@210e358"], #'clojure.core/*1 nil, #'cljs.analyzer/*cljs-warnings* {:invoke-ctor true, :extending-base-js-type true, :unsupported-preprocess-value true, :redef true, :js-shadowed-by-local true, :unsupported-js-module-type true, :invalid-protocol-symbol true, :protocol-duped-method true, :munged-namespace true, :single-segment-namespace true, :fn-arity true, :infer-warning false, :variadic-max-arity true, :protocol-with-variadic-method true, :fn-deprecated true, :undeclared-var true, :preamble-missing true, :undeclared-protocol-symbol true, :dynamic true, :unprovided true, :ns-var-clash true, :undeclared-ns true, :undeclared-ns-form true, :invalid-arithmetic true, :protocol-deprecated true, :fn-var true, :overload-arity true, :protocol-multiple-impls true, :redef-in-file true, :protocol-invalid-method true, :extend-type-invalid-method-shape true, :multiple-variadic-overloads true}, #'clojure.core/*assert* true, #<Var: --unnamed--> nil, #'cljs.repl/*repl-opts* {:print-no-newline #object[clojure.core$print 0x2ddcb981 "clojure.core$print@2ddcb981"], :output-dir "target/cljsbuild/public/js/out", :flush #object[clojure.core$flush 0x6a491147 "clojure.core$flush@6a491147"], :closure-warnings {:check-types :off, :check-variables :off}, :wrap #object[figwheel_sidecar.repl$wrap_fn 0x69cab760 "figwheel_sidecar.repl$wrap_fn@69cab760"], :compiler-env #object[clojure.lang.Atom 0x23ad20c0 {:status :ready, :val #CompilerEnv{}}], :read #object[cljs.repl$repl_read 0x5fa8c5d9 "cljs.repl$repl_read@5fa8c5d9"], :ups-libs nil, :cache-analysis true, :closure-module-roots [], :special-fns {fig-status #object[figwheel_sidecar.system$make_special_fn$self__26838 0x4d9b9cc4 "figwheel_sidecar.system$make_special_fn$self__26838@4d9b9cc4"], stop-autobuild #object[figwheel_sidecar.system$make_special_fn$self__26838 0x49fc7e6a "figwheel_sidecar.system$make_special_fn$self__26838@49fc7e6a"], start-autobuild #object[figwheel_sidecar.system$make_special_fn$self__26838 0x42677756 "figwheel_sidecar.system$make_special_fn$self__26838@42677756"], build-once #object[figwheel_sidecar.system$make_special_fn$self__26838 0x7eaab9cd "figwheel_sidecar.system$make_special_fn$self__26838@7eaab9cd"], reload-config #object[figwheel_sidecar.system$make_special_fn$self__26838 0x6fc66760 "figwheel_sidecar.system$make_special_fn$self__26838@6fc66760"], switch-to-build #object[figwheel_sidecar.system$make_special_fn$self__26838 0x45e35bdc "figwheel_sidecar.system$make_special_fn$self__26838@45e35bdc"], print-config #object[figwheel_sidecar.system$make_special_fn$self__26838 0x3c4759f1 "figwheel_sidecar.system$make_special_fn$self__26838@3c4759f1"], clean-builds #object[figwheel_sidecar.system$make_special_fn$self__26838 0x1788fb65 "figwheel_sidecar.system$make_special_fn$self__26838@1788fb65"], reset-autobuild #object[figwheel_sidecar.system$make_special_fn$self__26838 0x4ba96393 "figwheel_sidecar.system$make_special_fn$self__26838@4ba96393"]}, :def-emits-var true, :optimizations :none, :ups-foreign-libs [], :print #object[clojure.core$println 0x705ccb05 "clojure.core$println@705ccb05"], :source-map-inline true, :output-to "target/cljsbuild/public/js/app.js", :source-map-timestamp true, :prompt #object[figwheel_sidecar.repl$prompt_fn$fn__25515 0x144bfc81 "figwheel_sidecar.repl$prompt_fn$fn__25515@144bfc81"], :preamble ["cljs/imul.js"], :asset-path "/js/out", :warn-on-undeclared true, :ups-externs nil, :reader #object[cljs.repl$repl_STAR_$fn__15088 0x46f60697 "cljs.repl$repl_STAR_$fn__15088@46f60697"], :source-map true, :foreign-libs [], :need-prompt #object[cljs.repl$repl_STAR_$fn__15090 0x23a258e7 "cljs.repl$repl_STAR_$fn__15090@23a258e7"], :cache-analysis-format :transit, :main "luminuscljs.app", :pretty-print true, :caught #object[cljs.repl$repl_caught 0x6c57f74e "cljs.repl$repl_caught@6c57f74e"], :emit-constants nil, :eval #'figwheel-sidecar.repl/catch-warnings-and-exceptions-eval-cljs}, #'clojure.core/*warn-on-reflection* nil, #'clojure.core/*3 nil, #<Var: --unnamed--> nil, #<Var: --unnamed--> 0, #<Var: --unnamed--> 1, #'clojure.core/*ns* #object[clojure.lang.Namespace 0x1b89d2ea "user"], #'cljs.analyzer/*cljs-file* "<cljs repl>", #'clojure.core/*print-length* nil, #'clojure.core/*2 nil, #'cljs.analyzer/*cljs-static-fns* nil, #<Var: --unnamed--> 187, #'clojure.core/*compile-path* "null", #'clojure.core/*e nil, #'clojure.core/*data-readers* {spy/p #'spyscope.core/print-log, ds/trie #'data-scope.graphs/scope-trie, ds/p-max #'data-scope.charts/scope-pie-max, ds/p-max* #'data-scope.charts/scope-pie-max*, ds/a-min #'data-scope.charts/scope-area-min, ds/hf #'data-scope.charts/scope-histogram-frequency, spy/t #'spyscope.core/trace, ds/l-min #'data-scope.charts/scope-line-min, ds/it #'data-scope.inspect/scope-inspect-table, ds/sa #'data-scope.charts/scope-stacked-area, ds/sa-min* #'data-scope.charts/scope-stacked-area-min*, ds/b-min* #'data-scope.charts/scope-bar-min*, ds/a-min* #'data-scope.charts/scope-area-min*, ds/b-sum #'data-scope.charts/scope-bar-sum, ds/l #'data-scope.charts/scope-line, ds/l-max* #'data-scope.charts/scope-line-max*, ds/b-max #'data-scope.charts/scope-bar-max, ds/graph #'data-scope.graphs/scope-graph, ds/b #'data-scope.charts/scope-bar, ds/sa-max* #'data-scope.charts/scope-stacked-area-max*, ds/a-sum* #'data-scope.charts/scope-area-sum*, ds/b-sum* #'data-scope.charts/scope-bar-sum*, ds/sa-sum #'data-scope.charts/scope-stacked-area-sum, ds/dot #'data-scope.graphs/scope-dot, spy/d #'spyscope.core/print-log-detailed, ds/a-max* #'data-scope.charts/scope-area-max*, ds/p-min #'data-scope.charts/scope-pie-min, ds/a #'data-scope.charts/scope-area, ds/a-max #'data-scope.charts/scope-area-max, ds/p-min* #'data-scope.charts/scope-pie-min*, ds/p #'data-scope.charts/scope-pie, ds/hd #'data-scope.charts/scope-histogram-density, ds/l-sum #'data-scope.charts/scope-line-sum, ds/i #'data-scope.inspect/scope-inspect-tree, ds/p-sum #'data-scope.charts/scope-pie-sum, ds/sa-max #'data-scope.charts/scope-stacked-area-max, ds/b-min #'data-scope.charts/scope-bar-min, ds/tree #'data-scope.graphs/scope-tree, ds/pt #'data-scope.pprint/scope-print-table, ds/a-sum #'data-scope.charts/scope-area-sum, ds/l-max #'data-scope.charts/scope-line-max, ds/sa-min #'data-scope.charts/scope-stacked-area-min, ds/pp #'data-scope.pprint/scope-pprint, ds/sa-sum* #'data-scope.charts/scope-stacked-area-sum*, ds/l-min* #'data-scope.charts/scope-line-min*, ds/b-max* #'data-scope.charts/scope-bar-max*, ds/l-sum* #'data-scope.charts/scope-line-sum*, ds/p-sum* #'data-scope.charts/scope-pie-sum*}, #<Var: --unnamed--> 1, #'clojure.core/*file* "C:\\Users\\mark\\AppData\\Local\\Temp\\form-init2963028086917439510.clj", #<Var: --unnamed--> 107, #<Var: --unnamed--> #object[clojure.lang.DynamicClassLoader 0x1b37d701 "clojure.lang.DynamicClassLoader@1b37d701"], #'clojure.core/*unchecked-math* false, #'clojure.core/*default-data-reader-fn* nil, #'clojure.core/*read-eval* true, #'clojure.core/*source-path* "form-init2963028086917439510.clj", #'cljs.analyzer/*cljs-ns* cljs.user, #'clojure.core/*print-meta* false}}]}, :repl-opts {:output-dir "target/cljsbuild/public/js/out", :wrap #object[figwheel_sidecar.repl$wrap_fn 0x69cab760 "figwheel_sidecar.repl$wrap_fn@69cab760"], :compiler-env #object[clojure.lang.Atom 0x23ad20c0 {:status :ready, :val #CompilerEnv{}}], :special-fns {fig-status #object[figwheel_sidecar.system$make_special_fn$self__26838 0x4d9b9cc4 "figwheel_sidecar.system$make_special_fn$self__26838@4d9b9cc4"], stop-autobuild #object[figwheel_sidecar.system$make_special_fn$self__26838 0x49fc7e6a "figwheel_sidecar.system$make_special_fn$self__26838@49fc7e6a"], start-autobuild #object[figwheel_sidecar.system$make_special_fn$self__26838 0x42677756 "figwheel_sidecar.system$make_special_fn$self__26838@42677756"], build-once #object[figwheel_sidecar.system$make_special_fn$self__26838 0x7eaab9cd "figwheel_sidecar.system$make_special_fn$self__26838@7eaab9cd"], reload-config #object[figwheel_sidecar.system$make_special_fn$self__26838 0x6fc66760 "figwheel_sidecar.system$make_special_fn$self__26838@6fc66760"], switch-to-build #object[figwheel_sidecar.system$make_special_fn$self__26838 0x45e35bdc "figwheel_sidecar.system$make_special_fn$self__26838@45e35bdc"], print-config #object[figwheel_sidecar.system$make_special_fn$self__26838 0x3c4759f1 "figwheel_sidecar.system$make_special_fn$self__26838@3c4759f1"], clean-builds #object[figwheel_sidecar.system$make_special_fn$self__26838 0x1788fb65 "figwheel_sidecar.system$make_special_fn$self__26838@1788fb65"], reset-autobuild #object[figwheel_sidecar.system$make_special_fn$self__26838 0x4ba96393 "figwheel_sidecar.system$make_special_fn$self__26838@4ba96393"]}, :optimizations :none, :output-to "target/cljsbuild/public/js/app.js", :source-map-timestamp true, :prompt #object[figwheel_sidecar.repl$prompt_fn$fn__25515 0x144bfc81 "figwheel_sidecar.repl$prompt_fn$fn__25515@144bfc81"], :asset-path "/js/out", :warn-on-undeclared true, :source-map true, :main "luminuscljs.app", :pretty-print true, :eval #'figwheel-sidecar.repl/catch-warnings-and-exceptions-eval-cljs}, :cljs.env/compiler #object[clojure.lang.Atom 0x23ad20c0 {:status :ready, :val #CompilerEnv{}}]}, :form (set! cljs.core/*print-namespace-maps* true), :js "cljs.core._STAR_print_namespace_maps_STAR_ = true"}
        at clojure.core$ex_info.invokeStatic(core.clj:4617)
        at clojure.core$ex_info.invoke(core.clj:4617)
        at cljs.repl$evaluate_form.invokeStatic(repl.cljc:504)
        at cljs.repl$evaluate_form.invoke(repl.cljc:443)
        at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:832)
        at cljs.repl$repl_STAR_.invoke(repl.cljc:737)
        at figwheel_sidecar.repl$eval25487$fn__25488.invoke(repl.clj:186)
        at clojure.lang.MultiFn.invoke(MultiFn.java:233)
        at figwheel_sidecar.repl$repl.invokeStatic(repl.clj:305)
        at figwheel_sidecar.repl$repl.doInvoke(repl.clj:303)
        at clojure.lang.RestFn.invoke(RestFn.java:436)
        at figwheel_sidecar.system$start_figwheel_repl.invokeStatic(system.clj:510)
        at figwheel_sidecar.system$start_figwheel_repl.invoke(system.clj:501)
        at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invokeStatic(system.clj:574)
        at figwheel_sidecar.system$figwheel_cljs_repl_STAR_.invoke(system.clj:572)
        at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invokeStatic(system.clj:580)
        at figwheel_sidecar.system$build_switching_cljs_repl_STAR_.invoke(system.clj:576)
        at figwheel_sidecar.system$cljs_repl_STAR_.invokeStatic(system.clj:596)
        at figwheel_sidecar.system$cljs_repl_STAR_.invoke(system.clj:587)
        at figwheel_sidecar.system$start_repl.invokeStatic(system.clj:621)
        at figwheel_sidecar.system$start_repl.invoke(system.clj:615)
        at figwheel_sidecar.system$start_repl.invokeStatic(system.clj:617)
        at figwheel_sidecar.system$start_repl.invoke(system.clj:615)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$apply.invoke(core.clj:641)
        at figwheel_sidecar.system$cljs_repl.invokeStatic(system.clj:629)
        at figwheel_sidecar.system$cljs_repl.doInvoke(system.clj:627)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at figwheel_sidecar.repl_api$start_figwheel_from_lein.invokeStatic(repl_api.clj:156)
        at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:147)
        at figwheel_sidecar.repl_api$launch_from_lein.invokeStatic(repl_api.clj:223)
        at figwheel_sidecar.repl_api$launch_from_lein.invoke(repl_api.clj:215)
        at user$eval38219.invokeStatic(form-init2963028086917439510.clj:1)
        at user$eval38219.invoke(form-init2963028086917439510.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6917)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$init_opt.invokeStatic(main.clj:277)
        at clojure.main$init_opt.invoke(main.clj:277)
        at clojure.main$initialize.invokeStatic(main.clj:308)
        at clojure.main$null_opt.invokeStatic(main.clj:342)
        at clojure.main$null_opt.invoke(main.clj:339)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Subprocess failed
```

**Comment by yogthos** [comment]
I'm actually not able to reproduce the problem locally. I made a new project using the `+cljs` profile, and switched Clojure version to `1.9.0-alpha16`. I started up lein run/lein figwheel and I'm not seeing errors in either terminal after Figwheel connects to the browser. I left it running for a few minutes as you suggested.

There was a [recent change](https://groups.google.com/forum/#!msg/clojure/10dbF7w2IQo/ec37TzP5AQAJ) where spec namespaces were moved to spec.alpha, I can't think of a reason that should cause the error you're seeing though.

One thing to check would be if you have any plugins in your `~/.lein/profiles.clj` that might affect this.

**Comment by Engelberg** [comment]
In my latest replication of the error, I kept Clojure at 1.8.0 from the +cljs profile, and still had a problem.  I made no modifications to the new template whatsoever, and still had the problem.

Then, I restored using version control to a commit from last week, and everything works fine.

Same basic dependencies, although there are several minor version differences.  figwheel and figwheel-sidecar were on 0.5.9 instead of 0.5.10, for example, in my file last week.

I'm puzzled that you're not seeing it.  I will check my profiles.clj as you suggested.

**Comment by Engelberg** [comment]
Ok, I've got it working.  It appears to have been caused by my upgrade of figwheel and figwheel-sidecar to 0.5.10.  Somehow my browser was caching an older version, causing problems.  By opening the developer console to force a refresh without cache, everything is happy again.  Sorry for taking your time.  Thanks for your help.

**Comment by yogthos** [comment]
Ah yes, I've been bit by that before. Glad everything's working. As a side note, if you're making a new project with `+hoplon`, you don't have to also add `+cljs`. The profiles track dependencies, and luminus knows to automatically inject cljs profile when hoplon is used.
